stages:
  - test-unit
  - test-e2e
  - build
  - deploy

default:
  image:
    name: mcr.microsoft.com/dotnet/aspnet:6.0-focal
    entrypoint: [""]

unit_test_project:
  tags:
    - sopro
  stage: test-unit
  script:
  - echo "Unit test job."

e2e_test_project:
  tags:
    - sopro
  stage: test-e2e
  script:
  - echo "E2E test job."

build_project:
  tags:
    - sopro
  stage: build
  script:
  - echo "Build project job."

deploy_project:
  tags:
    - sopro
  stage: deploy
  script:
  - echo "Deploy project job."


include:
  - local: "/Abgaben/Uebungsblatt6/Einzelabgaben/Tornquist/SoPro24Team06/.gitlab-ci.yml"
  - local: "/Abgaben/Uebungsblatt5/Einzelabgaben/Adolf/SoPro24Team06/.gitlab-ci.yml"
  - local: "/Abgaben/Uebungsblatt6/Einzelabgaben/Pfluger/SoPro24Team06/.gitlab-ci.yml"
  - local: "/Abgaben/Uebungsblatt7/Einzelabgaben/Varadi/SoPro24Team06/.gitlab-ci.yml"
  - local: "/Abgaben/Uebungsblatt6/Einzelabgaben/Steiner/SoPro24Team06/.gitlab-ci.yml"
