@startuml
    object Rolle
        Rolle : ID
        Rolle : Name

    object Benutzer
        Benutzer : ID
        Benutzer : Name
        Benutzer : E-Mail
        Benutzer : Gesperrt

    object Administrator

    object Mitarbeiter
        Mitarbeiter : ID
        Mitarbeiter : Name


    object Prozess
        Prozess : ID
        Prozess : Name
        Prozess : Beschreibung



    object Vorgang
        Vorgang : ID
        Vorgang : Name
        Vorgang : ErstelltAm
        Vorgang : FertigBis


    object Aufgabe
        Aufgabe : ID
        Aufgabe : Name
        Aufgabe : Anleitung
        Aufgabe : Status
        Aufgabe : ZuErledigenBis


    object Abteilung
        Abteilung : ID
        Abteilung : Name

    Benutzer "1" -- "1..*" Rolle : > hat
    Benutzer "1" -- "1" Abteilung : > hat
    Benutzer "1" -- "*" Aufgabe : > erledigt
      
    Administrator ---|> Rolle
    Administrator "1" -- "*" Prozess : > verwaltet
    Administrator "1" -- "*" Benutzer : > verwaltet

    Prozess "*" -- "*" Rolle : < verwaltet
    Prozess "1" -- "1..*" Aufgabe : > enthält
      
    Vorgang "*" -- "1" Mitarbeiter :< verantwortlich für
    Vorgang "*" -- "1" Mitarbeiter :< Bezugsperson von
    Vorgang ---|> Prozess

    Aufgabe "*" -- "*" Benutzer : < erhält
    Aufgabe "*" -- "*" Rolle : < erhält
    Aufgabe "*" -- "*" Abteilung : < erhält
@enduml
