@startuml
!pragma layout elk

    object Rolle
        Rolle : Name

    object Benutzer
        Benutzer : Name
        Benutzer : E-Mail
        Benutzer : Gesperrt

    object Administrator

    ' object Mitarbeiter
    '     Mitarbeiter : Name

    
    object Bezugsperson
    
    object Aufgabenzuständiger
    
    object Vorgangsverantwortliche    
    


    object Prozess
        Prozess : Name
        Prozess : Beschreibung



    object Vorgang
        Vorgang : Name
        Vorgang : Vertragstyp
        Vorgang : ErstelltAm
        Vorgang : Zieldatum


    object Aufgabe
        Aufgabe : Name
        Aufgabe : Anleitung
        Aufgabe : Vertragsart
        Aufgabe : Status
        Aufgabe : Zieldatum


    object Abteilung
        Abteilung : Name

    Benutzer "1" -- "1..*" Rolle : > hat
    Benutzer "1" -- "1" Abteilung : > hat
    ' Benutzer "1" -- "*" Aufgabe : > erledigt
    ' Benutzer "1" -- "1" Mitarbeiter : > ist ein
    Benutzer <|--- Bezugsperson
    Benutzer --- Aufgabenzuständiger  : < ist ein
    Benutzer --- Vorgangsverantwortliche  : < ist ein


    ' Mitarbeiter "1" -- "1..*" Rolle : > hat
    ' Mitarbeiter "1" -- "1" Abteilung : > gehört zu
    ' Mitarbeiter "1" -- "*" Aufgabe : > erledigt
    ' Mitarbeiter <|--- Bezugsperson
    ' Mitarbeiter <|--- Aufgabenzuständiger
    ' Mitarbeiter <|--- Vorgangsverantwortliche
    
      
    Administrator ---|> Rolle
    Administrator "1" -- "*" Prozess : > verwaltet
    Administrator "1" -- "*" Benutzer : > verwaltet

    Prozess "*" -- "*" Rolle : < hat Zugriff auf
    Prozess "1..*" -- "1..*" Aufgabe : > enthält
    Prozess "1" -- "*" Vorgang : < hat als vorlage
      
    Vorgang "1" -- "1" Vorgangsverantwortliche : < verwaltet
    Vorgang "1" -- "1" Bezugsperson
    Vorgang "1" -- "1..*" Aufgabe : > enthält

    Aufgabe "1" -- "*" Benutzer : < zuständig für und erledigt
    Aufgabe "1" -- "*" Rolle : < zuständig für
    Aufgabe "1" -- "*" Abteilung : > eingeschränkt auf
    Aufgabe "1" -- "1..*" Aufgabenzuständiger : < verwaltet
    Aufgabe  --  Vorgangsverantwortliche : < verwaltet
@enduml
