@startuml
      
      class Rolle {
            ID
            Name           
      }

      class Benutzer {
            ID
            Name
            E-Mail
            Gesperrt

      }

      class Administrator {}
      
      class Prozess{
            ID
            Name
            Beschreibung
      }


      class Vorgang{
            ID
            Name
            ErstelltAm
            FertigBis
      }

      class Aufgabe {
            ID
            Name
            Anleitung
            Status
            ZuErledigenBis
            
      }

      class Abteilung {
            ID
            Name
      }

      Benutzer "1" -- "1..*" Rolle : > hat
      Benutzer "1" -- "1" Abteilung : > hat
      Benutzer "1" -- "*" Aufgabe : > erledigt
      
      Administrator ---|> Rolle
      Administrator "1" -- "*" Prozess : > verwaltet
      Administrator "1" -- "*" Benutzer : > verwaltet

      Prozess "*" -- "*" Rolle : < verwaltet
      Prozess "1" -- "1..*" Aufgabe : > erhält
      
      Vorgang "1" -- "*" Benutzer :< zuständig für
      Vorgang "1" -- "*" Benutzer :< Bezugsperson von
      Vorgang ---|> Prozess

      Aufgabe "1" -- "*" Benutzer : < bekommt
      Aufgabe "1" -- "*" Rolle : < bekommt
      Aufgabe "1" -- "*" Abteilung : < bekommt




@enduml
